### ISSUE TITLE
Panic when resizing window below certain size when app is in finished state

### ISSUE THREAD

**Issue by LMH01** [LMH01/alpha_tui#65]
When the app is in the finished state and the display size is reduced below a certain threshold, the program panics. It seems like this issue occurs at the moment, when the stack should no longer be displayed.

**Comment by LMH01** [comment]
I was able to get a stacktrace (all though quite ugly):

```
thread 'main' panicked at /home/louis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.26.1/src/widgets/list.rs:901:28:
           attempt to subtract with overflow
  stack backtrace:
                     0: rust_begin_unwind
                       1: core::panicking::panic_fmt
             2: core::panicking::panic
                    3: <ratatui::widgets::list::List as ratatui::widgets::StatefulWidgetRef>::render_ref
                                 at /home/louis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.26.1/src/widgets/list.rs:901:28
                   4: <ratatui::widgets::list::List as ratatui::widgets::StatefulWidget>::render
                         at /home/louis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.26.1/src/widgets/list.rs:831:9
          5: ratatui::terminal::frame::Frame::render_stateful_widget
                  at /home/louis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.26.1/src/terminal/frame.rs:125:9
     6: alpha_tui::app::ui::draw
                        at ./src/app/ui.rs:134:5
         7: alpha_tui::app::App::run::{{closure}}
                    at ./src/app/mod.rs:154:31
       8: ratatui::terminal::terminal::Terminal<B>::draw
                           at /home/louis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.26.1/src/terminal/terminal.rs:269:9
                 9: alpha_tui::app::App::run
               at ./src/app/mod.rs:154:13
                      10: alpha_tui::app::commands::load::load
                                 at ./src/app/commands/load.rs:63:15
       11: alpha_tui::main
                  at ./src/main.rs:46:37
                     12: core::ops::function::FnOnce::call_once
             at /build/rustc-1.76.0-src/library/core/src/ops/function.rs:250:5
               note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

So the issue seems to be related to ratatui. It also seems like this issue is fixed in ratatui v26.2.0 but we are unable to upgrade because this version introduces another bug, that also causes a panic. So until ratatui is fixed and upgraded, this issue will be unfixable.

**Comment by LMH01** [comment]
This panic also occurs when the app is in running state.

**Comment by LMH01** [comment]
Ratatui has received a new version (v0.26.3), so the issue should be fixed.

**Comment by LMH01** [comment]
for testing ratatui was upgraded to v0.26.3 and it seems like the issue is gone. Marking as closed and will be included in the next release.
